export interface GlobeLocation {
  id: string;
  label: string;
  lat: number;
  lng: number;
  category: "institution" | "event" | "document" | "military" | "corporate" | "government";
  description: string;
  sourceCount: number;
  evidenceIds: string[];
  color: string;
  size: number;
}

export const CATEGORY_COLORS: Record<string, string> = {
  institution: "#00e5ff",
  event: "#ff6b35",
  document: "#a78bfa",
  military: "#ef4444",
  corporate: "#22c55e",
  government: "#f59e0b",
};

export const demoGlobeLocations: GlobeLocation[] = [
  {
    id: "loc-1",
    label: "NSA Headquarters",
    lat: 39.1087,
    lng: -76.7717,
    category: "military",
    description: "National Security Agency, Fort Meade, Maryland. Central hub for signals intelligence (SIGINT) and information assurance. Key node in PRISM surveillance program documentation.",
    sourceCount: 14,
    evidenceIds: ["ev-1", "ev-2"],
    color: CATEGORY_COLORS.military,
    size: 1.2,
  },
  {
    id: "loc-2",
    label: "Google HQ (Googleplex)",
    lat: 37.422,
    lng: -122.084,
    category: "corporate",
    description: "Alphabet Inc. headquarters, Mountain View, CA. Named in PRISM program documents as data provider. Subject of multiple antitrust investigations.",
    sourceCount: 9,
    evidenceIds: ["ev-3"],
    color: CATEGORY_COLORS.corporate,
    size: 1.0,
  },
  {
    id: "loc-3",
    label: "The Pentagon",
    lat: 38.8719,
    lng: -77.0563,
    category: "military",
    description: "United States Department of Defense headquarters. Arlington, VA. Central command for military operations and defense policy.",
    sourceCount: 22,
    evidenceIds: ["ev-1"],
    color: CATEGORY_COLORS.military,
    size: 1.4,
  },
  {
    id: "loc-4",
    label: "U.S. Capitol Building",
    lat: 38.8899,
    lng: -77.0091,
    category: "government",
    description: "Seat of the United States Congress. Washington, D.C. Origin point for legislation including the Patriot Act, FISA Amendments Act, and intelligence oversight committees.",
    sourceCount: 18,
    evidenceIds: ["ev-4", "ev-5"],
    color: CATEGORY_COLORS.government,
    size: 1.3,
  },
  {
    id: "loc-5",
    label: "GCHQ Cheltenham",
    lat: 51.8985,
    lng: -2.1244,
    category: "institution",
    description: "Government Communications Headquarters, UK. Five Eyes alliance member. Documented in Tempora program for mass interception of fiber-optic communications.",
    sourceCount: 11,
    evidenceIds: ["ev-2"],
    color: CATEGORY_COLORS.institution,
    size: 1.1,
  },
  {
    id: "loc-6",
    label: "European Parliament",
    lat: 48.5972,
    lng: 7.7684,
    category: "government",
    description: "Strasbourg, France. Passed GDPR in response to surveillance revelations. Multiple resolutions on mass surveillance and digital rights.",
    sourceCount: 7,
    evidenceIds: ["ev-6"],
    color: CATEGORY_COLORS.government,
    size: 0.9,
  },
  {
    id: "loc-7",
    label: "Meta (Facebook) HQ",
    lat: 37.4845,
    lng: -122.1477,
    category: "corporate",
    description: "Meta Platforms headquarters, Menlo Park, CA. Named in PRISM documents. Subject of Cambridge Analytica data scandal investigations.",
    sourceCount: 12,
    evidenceIds: ["ev-3"],
    color: CATEGORY_COLORS.corporate,
    size: 1.0,
  },
  {
    id: "loc-8",
    label: "Kremlin",
    lat: 55.7520,
    lng: 37.6175,
    category: "government",
    description: "Seat of Russian government, Moscow. Subject of multiple intelligence reports regarding election interference and cyber operations.",
    sourceCount: 15,
    evidenceIds: ["ev-7"],
    color: CATEGORY_COLORS.government,
    size: 1.2,
  },
  {
    id: "loc-9",
    label: "Pine Gap",
    lat: -23.7991,
    lng: 133.7370,
    category: "military",
    description: "Joint Defence Facility Pine Gap, Australia. Five Eyes satellite surveillance station. Jointly operated by Australia and the United States.",
    sourceCount: 6,
    evidenceIds: ["ev-2"],
    color: CATEGORY_COLORS.military,
    size: 0.8,
  },
  {
    id: "loc-10",
    label: "DARPA HQ",
    lat: 38.8814,
    lng: -77.1114,
    category: "institution",
    description: "Defense Advanced Research Projects Agency, Arlington, VA. Origin of foundational internet technology (ARPANET). Ongoing advanced research programs.",
    sourceCount: 10,
    evidenceIds: ["ev-1"],
    color: CATEGORY_COLORS.institution,
    size: 1.0,
  },
  {
    id: "loc-11",
    label: "UN Headquarters",
    lat: 40.7489,
    lng: -73.9680,
    category: "institution",
    description: "United Nations, New York City. International governance body. Subject of surveillance by multiple state actors per leaked documents.",
    sourceCount: 8,
    evidenceIds: ["ev-8"],
    color: CATEGORY_COLORS.institution,
    size: 1.1,
  },
  {
    id: "loc-12",
    label: "Shenzhen Tech District",
    lat: 22.5431,
    lng: 114.0579,
    category: "corporate",
    description: "Major technology manufacturing hub, China. Home to Huawei, Tencent, and ZTE. Subject of supply chain security investigations.",
    sourceCount: 9,
    evidenceIds: ["ev-9"],
    color: CATEGORY_COLORS.corporate,
    size: 1.0,
  },
  {
    id: "loc-13",
    label: "CERN",
    lat: 46.2330,
    lng: 6.0557,
    category: "institution",
    description: "European Organization for Nuclear Research, Geneva. Birthplace of the World Wide Web. Advanced physics research facility.",
    sourceCount: 5,
    evidenceIds: ["ev-10"],
    color: CATEGORY_COLORS.institution,
    size: 0.8,
  },
  {
    id: "loc-14",
    label: "Langley (CIA HQ)",
    lat: 38.9517,
    lng: -77.1467,
    category: "military",
    description: "Central Intelligence Agency headquarters, Langley, VA. Primary U.S. human intelligence (HUMINT) agency. Subject of extensive declassified documentation.",
    sourceCount: 25,
    evidenceIds: ["ev-1", "ev-7"],
    color: CATEGORY_COLORS.military,
    size: 1.5,
  },
  {
    id: "loc-15",
    label: "Bank of England",
    lat: 51.5142,
    lng: -0.0885,
    category: "institution",
    description: "Central bank of the United Kingdom, London. Key node in global financial system. Subject of monetary policy investigations.",
    sourceCount: 7,
    evidenceIds: ["ev-11"],
    color: CATEGORY_COLORS.institution,
    size: 0.9,
  },
  {
    id: "loc-16",
    label: "Federal Reserve",
    lat: 38.8928,
    lng: -77.0452,
    category: "institution",
    description: "Board of Governors, Washington D.C. Central banking system of the United States. Subject of extensive monetary policy and transparency debates.",
    sourceCount: 13,
    evidenceIds: ["ev-11", "ev-12"],
    color: CATEGORY_COLORS.institution,
    size: 1.2,
  },
  {
    id: "loc-17",
    label: "Davos (WEF)",
    lat: 46.8027,
    lng: 9.8360,
    category: "event",
    description: "World Economic Forum annual meeting location, Davos, Switzerland. Global elite gathering for economic and political discussions.",
    sourceCount: 6,
    evidenceIds: ["ev-13"],
    color: CATEGORY_COLORS.event,
    size: 0.9,
  },
  {
    id: "loc-18",
    label: "Bohemian Grove",
    lat: 38.4741,
    lng: -123.0008,
    category: "event",
    description: "Monte Rio, California. Private campground hosting annual gathering of prominent figures. Documented by investigative journalists.",
    sourceCount: 4,
    evidenceIds: ["ev-14"],
    color: CATEGORY_COLORS.event,
    size: 0.7,
  },
];
