project_id = "sijocrtrjpbkwjbihgok"

[functions.globe-query]
verify_jwt = false

[functions.rabbit-hole]
verify_jwt = false

[functions.ingest-news]
verify_jwt = false

[functions.ingest-twitter]
verify_jwt = false

[functions.ingest-documents]
verify_jwt = false

[functions.process-intelligence]
verify_jwt = false

[functions.fact-check]
verify_jwt = false

[functions.ingest-bulk-documents]
verify_jwt = false

[functions.search-documents]
verify_jwt = false
